[book]
authors = ["Renoise"]
language = "en"
multilingual = false
src = "docs"
title = "Renoise Scripting"

[build]
extra-watch-dirs = [
  "library",
  "scripts/mdbook-luacats"
]

[preprocessor.luacats]
command = "lua scripts/mdbook-luacats/init.lua"
definitions-path = "library"